[package]
name = "kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
verifier = { path = "../verifier" }
slots = { path = "../slots" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
